.\" Manpage for superscs.
.\" Contact p.sopasakis@gmail.com to correct errors or typos.
.TH man 8 "06 May 2010" "1.3.3" "superscs man page"
.SH NAME
superscs \- fast and accurate solver for conic programs
.SH SYNOPSIS
nuseradd [USERNAME]
.SH DESCRIPTION
superescs is a fast solver for conic programs.
.SH OPTIONS
Several options 
.SH BUGS
No known bugs.
.SH AUTHOR
Pantelis Sopasakis (p.sopasakis@gmail.com)
