function dR = dEuler_to_dMatrix(in1,in2)
%DEULER_TO_DMATRIX
%    DR = DEULER_TO_DMATRIX(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2019 11:01:04

dpitch = in2(2,:);
droll_angle = in2(3,:);
dyaw = in2(1,:);
pitch = in1(2,:);
roll_angle = in1(3,:);
yaw = in1(1,:);
t2 = sin(yaw);
t3 = cos(yaw);
t4 = sin(pitch);
t5 = cos(roll_angle);
t6 = sin(roll_angle);
t7 = cos(pitch);
t8 = t3.*t6;
t9 = t8-t2.*t4.*t5;
t10 = t2.*t5;
t11 = t10-t3.*t4.*t6;
t12 = t3.*t5;
t13 = t2.*t4.*t6;
t14 = t12+t13;
t15 = t2.*t6;
t16 = t3.*t4.*t5;
t17 = t15+t16;
dR = reshape([-dpitch.*t3.*t4-dyaw.*t2.*t7,-dpitch.*t2.*t4+dyaw.*t3.*t7,-dpitch.*t7,droll_angle.*t17-dyaw.*t14+dpitch.*t3.*t6.*t7,-droll_angle.*t9-dyaw.*t11+dpitch.*t2.*t6.*t7,-dpitch.*t4.*t6+droll_angle.*t5.*t7,droll_angle.*t11+dyaw.*t9+dpitch.*t3.*t5.*t7,-droll_angle.*t14+dyaw.*t17+dpitch.*t2.*t5.*t7,-dpitch.*t4.*t5-droll_angle.*t6.*t7],[3,3]);
