function w = dMatrix_to_AngularVelocity(in1,in2)
%DMATRIX_TO_ANGULARVELOCITY
%    W = DMATRIX_TO_ANGULARVELOCITY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2019 11:01:03

dr1_1 = in2(1);
dr1_2 = in2(4);
dr1_3 = in2(7);
dr2_1 = in2(2);
dr2_2 = in2(5);
dr2_3 = in2(8);
dr3_1 = in2(3);
dr3_2 = in2(6);
dr3_3 = in2(9);
r1_1 = in1(1);
r1_2 = in1(4);
r1_3 = in1(7);
r2_1 = in1(2);
r2_2 = in1(5);
r2_3 = in1(8);
r3_1 = in1(3);
r3_2 = in1(6);
r3_3 = in1(9);
t2 = r1_1.*r2_2.*r3_3;
t3 = r1_2.*r2_3.*r3_1;
t4 = r1_3.*r2_1.*r3_2;
t7 = r1_1.*r2_3.*r3_2;
t8 = r1_2.*r2_1.*r3_3;
t9 = r1_3.*r2_2.*r3_1;
t5 = t2+t3+t4-t7-t8-t9;
t6 = 1.0./t5;
w = [dr3_2.*t6.*(r1_1.*r2_2-r1_2.*r2_1)-dr2_2.*t6.*(r1_1.*r3_2-r1_2.*r3_1)+dr1_2.*t6.*(r2_1.*r3_2-r2_2.*r3_1);dr3_3.*t6.*(r1_2.*r2_3-r1_3.*r2_2)-dr2_3.*t6.*(r1_2.*r3_3-r1_3.*r3_2)+dr1_3.*t6.*(r2_2.*r3_3-r2_3.*r3_2);-dr3_1.*t6.*(r1_1.*r2_3-r1_3.*r2_1)+dr2_1.*t6.*(r1_1.*r3_3-r1_3.*r3_1)-dr1_1.*t6.*(r2_1.*r3_3-r2_3.*r3_1)];
