function R = Euler_to_Matrix(in1)
%EULER_TO_MATRIX
%    R = EULER_TO_MATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2019 11:01:04

pitch = in1(2,:);
roll_angle = in1(3,:);
yaw = in1(1,:);
t2 = cos(yaw);
t3 = sin(roll_angle);
t4 = sin(yaw);
t5 = cos(roll_angle);
t6 = sin(pitch);
t7 = cos(pitch);
R = reshape([t2.*t7,t4.*t7,-t6,-t4.*t5+t2.*t3.*t6,t2.*t5+t3.*t4.*t6,t3.*t7,t3.*t4+t2.*t5.*t6,-t2.*t3+t4.*t5.*t6,t5.*t7],[3,3]);
