function q = Matrix_to_Quaternion(in1)
%MATRIX_TO_QUATERNION
%    Q = MATRIX_TO_QUATERNION(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2019 11:01:03

r1_1 = in1(1);
r1_2 = in1(4);
r1_3 = in1(7);
r2_1 = in1(2);
r2_2 = in1(5);
r2_3 = in1(8);
r3_1 = in1(3);
r3_2 = in1(6);
r3_3 = in1(9);
t2 = r1_1+r2_2+r3_3+1.0;
t3 = 1.0./sqrt(t2);
q = [sqrt(t2).*(1.0./2.0);t3.*(r2_3-r3_2).*(-1.0./2.0);t3.*(r1_3-r3_1).*(1.0./2.0);t3.*(r1_2-r2_1).*(-1.0./2.0)];
