function EA = Matrix_to_Euler(in1)
%MATRIX_TO_EULER
%    EA = MATRIX_TO_EULER(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    26-Mar-2019 11:01:58

r1_1 = in1(1);
r2_1 = in1(2);
r3_1 = in1(3);
r3_2 = in1(6);
r3_3 = in1(9);
EA = [angle(r1_1+r2_1.*1i);-asin(r3_1);angle(r3_2.*1i+r3_3)];
